input_dir: "data/input_excels"
table_name: "staging_maternas"
db_connection: "postgresql+psycopg2://postgres:admin123@localhost:5432/dbmaterna_mt"
apy_key: "AIzaSyDGhGk3DTCkjF1EUxpMm5ypFoQ-ecrS2gY"
output_dir_ent: "outfile/training"